### ISSUE TITLE
Unable to give space as special character.

### ISSUE THREAD

**Issue by pentanaveen** [ryanehrler/ngx-mask-ionic#1]
I'm trying to achieve something like this `Firstname lastname` but both special characters and custom patterns are not accepting space.

**Comment by ryanehrler** [comment]
Can I ask what mask you are using?  I'll check this out today.

**Comment by ryanehrler** [comment]
This worked for me.  The mask will keep the user from typing anything other than a letter.

`<ion-input formControlName="firstLast" [mask]="'A* A*'" [dropSpecialCharacters]="false" type="text" maxlength="14"></ion-input>`

If you want something more sophisticated you can go with a custom patttern.

`<ion-input formControlName="firstLast" [mask]="masks.firstLast.mask" [patterns]="masks.firstLast.pattern" [dropSpecialCharacters]="false" type="text"></ion-input>`

In your typescript.  You don't have to put these in your .ts if you don't want to.  You can just put them in your .html if you like.

`this.masks = {
      firstLast: {
        mask: '0* 0*',
        pattern: { '0': { pattern: /[a-zA-Z']/ } }
      }
    }`

If you need validation then you need to use a FormGroup and FormControls and add a custom validator.

**Comment by pentanaveen** [comment]
Thanks.I didn't mention `dropSpecialCharacters = false`.
